main:
  - name: Home
    url: /
    weight: 10

  - name: Publications
    url: /publications/
    weight: 11

  - name: Experience
    url: /experience/
    weight: 20

  - name: Gallery
    url: /gallery/
    weight: 30

  - name: Blog
    url: /blog/
    weight: 40
